/* Allegro data file object indexes */
/* Do not hand edit! */

#define ALIEN         0       /* spr */
#define BULLET        1       /* spr */
#define EXPLODE1      2       /* spr */
#define EXPLODE2      3       /* spr */
#define EXPLODE3      4       /* spr */
#define EXPLODE4      5       /* spr */
#define EXPLODE5      6       /* spr */
#define GAME_PAL      7       /* pal */
#define SHIP_GO       8       /* spr */
#define SHIP_STILL    9       /* spr */
#define TITLE_BMP     10      /* bmp */
#define TITLE_FONT    11      /* fnt */
#define TITLE_PAL     12      /* pal */
#define TITLE_TEXT    13      /* dat */
